name: skydroid_cli
description: Command-line tool for SkyDroid app distribution.
homepage: https://skydroid.dev
version: 0.1.3+13

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  path: ^1.0.0
  prompts: ^1.0.0
  yaml: ^2.0.0
  async: ^2.4.2
  crypto: ^3.0.0
  io: ^0.3.4
  json_schema2: ^2.0.0
  tint: ^2.0.0

executables:
  skydroid: skydroid
