name: skydroid_cli
description: Command-line tool for SkyDroid app distribution.
version: 0.1.0+1

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.0.0
  http: ^0.12.0
  path: ^1.0.0
  prompts: ^1.0.0
  yaml: ^2.0.0
  async: ^2.4.2
  crypto: ^2.1.5

executables:
  skydroid: skydroid

